import socket
s = socket.socket()
host=socket.gethostname()
port = 8080
s.bind((host,port))
s.listen(1)
print("Waiting for connection...")
conn1, addr1 = s.accept()
print("Client 1 has connected")
conn1.send("Welcome to the server".encode())
print("Waiting for connection...")
conn2, addr2 = s.accept()
print("Client 2 has connected")
conn2.send("Welcome to the server".encode())
conn3, addr3 = s.accept()
print("Client 3 has connected")
conn3.send("Welcome to the server".encode())
while 1:
	message = input(str("Type a message"))
	message = message.encode()
	conn1.send(message)
	conn2.send(message)
	conn3.send(message)
	print("Message sent...")
	recv_message = conn1.recv(1024)
	print("Client 1: ",recv_message.decode())
	print("Message sent...")
	recv_message = conn2.recv(1024)
	print("Client 1: ",recv_message.decode())
	print("Message sent...")
	recv_message = conn3.recv(1024)
	print("Client 3: ",recv_message.decode()